- name: Reading secrets from vault 
  hosts: localhost 
  tasks: 
    - name: Connect to Vault using TLS
      ansible.builtin.debug:
        msg: "Psw is {{secrets.mysql_pass}}"
      vars:
        secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=exp_app/data/backend token={{token}} url=https://vault.exp.in:8200 validate_certs=False') }}"